# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test before push

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Test with tox
      run: |
        tox

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Check
      run: |
        twine check dist/*
    - name: Publish
      env:
        TWINE_USERNAME:   ${{ secrets.TWINE_TEST_USERNAME }}
        TWINE_PASSWORD:   ${{ secrets.TWINE_TEST_PASSWORD }}
        TWINE_REPOSITORY: ${{ secrets.TWINE_TEST_REPOSITORY }}
      run: |
        twine upload --repository testpypi --verbose --non-interactive --disable-progress-bar --skip-existing dist/*
